name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build CYTools wheel
        run: |
          python -m build
          mkdir pypi
          cp dist/*.whl pypi/
          rm -rf dist/
      - name: Build the JupyterLite site
        run: |
          cp README.md content
          cd pypi/
          wget https://github.com/ariostas/python-flint-wasm/releases/download/v0.1.0/python_flint_wasm-0.5.0-cp311-cp311-emscripten_3_1_45_wasm32.whl
          jupyter piplite index
          cd ..
          jupyter lite build --contents content --output-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
